# Generated by Django 2.0.4 on 2018-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesouro',
            name='img_tesouro',
            field=models.ImageField(upload_to='imgs', verbose_name='Imagem'),
        ),
    ]
